const assert = require('node:assert/strict');
const fs = require('node:fs');
const { roundMoney, cents, isExactAmount, isGatewayPaymentExact, getCouponDiscount, isPaidStatus, isPayingStatus } = require('./server');

assert.equal(roundMoney(1.005), 1.01);
assert.equal(cents(9.99), 999);
assert.equal(isExactAmount(9.99, 9.99), true);
assert.equal(isExactAmount(9.98, 9.99), false);
assert.equal(isExactAmount(10, 9.99), false);
assert.equal(isGatewayPaymentExact({ amount: 9.99, value: 0.123, sent_value: 0.123 }, 9.99), true);
assert.equal(isGatewayPaymentExact({ amount: 9.99, value: 0.123, sent_value: 0.122 }, 9.99), false);
assert.equal(isGatewayPaymentExact({ amount: 9.98, value: 0.123, sent_value: 0.123 }, 9.99), false);
assert.equal(getCouponDiscount({ isActive: true, discountType: 'percentage', discountValue: 20 }, 10).discountAmount, 2);
assert.equal(getCouponDiscount({ isActive: true, discountType: 'percentage', discountValue: 80, maxDiscount: 3 }, 10).discountAmount, 3);
assert.equal(getCouponDiscount({ isActive: true, discountType: 'fixed', discountValue: 20 }, 10).discountAmount, 10);
assert.equal(getCouponDiscount({ isActive: true, discountType: 'percentage', discountValue: 20, usageLimit: 1, usedCount: 1 }, 10), null);
assert.equal(getCouponDiscount({ isActive: true, discountType: 'percentage', discountValue: 20, usageLimit: 1, reservedCount: 1 }, 10), null);
assert.equal(isPaidStatus('Paid'), true);
assert.equal(isPaidStatus('completed'), true);
assert.equal(isPaidStatus('paying'), false);
assert.equal(isPayingStatus('Paying'), true);
assert.equal(isPayingStatus('failed'), false);

const user = fs.readFileSync('./User.html', 'utf8');
const admin = fs.readFileSync('./admin.html', 'utf8');
const server = fs.readFileSync('./server.js', 'utf8');
assert.match(user, /startOxaPayCheckout/);
assert.match(user, /api\/payments/);
assert.match(user, /claimFreeProduct/);
assert.match(user, /dbRunTransaction/);
assert.match(user, /memberHubModal/);
assert.match(user, /api\/member\/overview/);
assert.match(user, /api\/products\/.*\/reviews/);
assert.match(user, /api\/games\/play/);
assert.match(user, /loadProductInsights/);
assert.match(user, /useCreditsToggle/);
assert.match(user, /redeemPointsFromHub/);
assert.doesNotMatch(user, /RTNBtWmc/);
assert.match(admin, /couponAutoDelete/);
assert.match(admin, /autoDelete/);
assert.match(admin, /insightConfirmedRevenue/);
assert.match(admin, /maintenanceModeToggle/);
assert.match(admin, /paymentAuditPreview/);
assert.match(server, /OXAPAY_MERCHANT_API_KEY/);
assert.equal(server.includes("createHmac('sha512'"), true);
assert.equal(server.includes('isGatewayPaymentExact(gateway, session.total)'), true);
assert.equal(server.includes('under_paid_coverage: 0'), true);
assert.equal(server.includes('mixed_payment: false'), true);
assert.equal(server.includes("paymentStatus: 'amount_mismatch'"), true);
assert.equal(server.includes('downloadMatch'), true);
assert.equal(server.includes('downloadOwnedFile'), true);
assert.equal(server.includes("pathname === '/api/member/overview'"), true);
assert.equal(server.includes("pathname === '/api/games/play'"), true);
assert.equal(server.includes("pathname === '/api/member/redeem-points'"), true);
assert.equal(server.includes('reserveCreditsForSession'), true);
assert.equal(server.includes('creditAmount'), true);
assert.equal(server.includes('scanPriceAlerts'), true);
assert.equal(server.includes('paymentEvents'), true);
assert.equal(server.includes('store/maintenance'), true);
assert.equal(fs.existsSync('./render.yaml'), true);
assert.doesNotMatch(server, /OXAPAY_MERCHANT_API_KEY\s*[:=]\s*['"][A-Za-z0-9_-]{20,}['"]/);
console.log('Smoke tests passed');
